externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: localhost:8000
info:
  contact:
    email: francisco@ithurriague.com
    name: Ithurriague Francisco
    url: https://ithurriague.com
  description: Personal portfolio
  termsOfService: http://swagger.io/terms/
  title: Swagger Example API
  version: "1.0"
paths:
  /:
    get:
      description: Builds and returns the home page file
      produces:
      - text/html
      responses:
        "200":
          description: Returns the home html page
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Home page
      tags:
      - controller
securityDefinitions:
  Authentication:
    in: header
    name: Bearer
    type: apiKey
swagger: "2.0"
